# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7e4923d79eedf6c78ec133722c8419bd850be982651e55110596c111b5a46c4ad2eca2eb9eeecedc20997643d3a066187b4420d02ab08842a5214330b55364b

test:
  secret_key_base: 722a4e474ecaf06845ca23ed3b15aaf7b9a075734d592488af60b89b4cf376a80c27de60d8558c670c7ea55b5dee316de6a9e336f7755330cbb37f4355b126a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
